version: '3.9'

services:
  nextjs:
    build: 
      context: .
      args:
        - BUILDKIT_PROGRESS=plain
    container_name: FE-Facillize
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - CI=true
      - DISABLE_ESLINT_PLUGIN=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "2"
        labels: "production"
    command: ["yarn", "start"]
    stdin_open: false
    tty: false
    networks:
      - facilize-network

  services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /root/FE-FACILIZE2/cert.crt:/cert.crt
      - /root/FE-FACILIZE2/cert.key:/cert.key
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - facilize-network

volumes:
  caddy_data:
  caddy_config:

networks:
  facilize-network:
    external: true