version: '3.9'

services:
  nextjs:
    build: 
      context: .
      args:
        - BUILDKIT_PROGRESS=plain
    container_name: FE-Facillize
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - CI=true
      - DISABLE_ESLINT_PLUGIN=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "2"
        labels: "production"
    command: ["yarn", "start"]
    stdin_open: false
    tty: false
    networks:
      - facilize-network

networks:
  facilize-network:
    external: true